### ISSUE TITLE
wcm seg fault when clicked on edit icon

### ISSUE THREAD

**Issue by librewish** [WayfireWM/wcm#12]
with new commit 
wcm crashes when clicked on edit icon.
to edit keybinding manually.
using wf-config = 0.3

**Comment by soreau** [comment]
@librewish Indeed, thanks for catching this.

**Comment by librewish** [comment]
also in core.xml default key which is 
alt KEY_FN_F4
is wrong
it should be
alt KEY_F4

**Comment by soreau** [comment]
> also in core.xml default key which is
> alt KEY_FN_F4
> is wrong
> it should be
> alt KEY_F4

It's KEY_FN_F4 in the [example config](https://github.com/WayfireWM/wayfire/blob/master/wayfire.ini.default#L12) and in [the source](https://github.com/WayfireWM/wayfire/blob/master/src/core/wm.cpp#L39), so core.xml is correct to match these.

**Comment by librewish** [comment]
but it doesn't work

**Comment by librewish** [comment]
KEY_F4
works for me when i press f4

**Comment by soreau** [comment]
@librewish If you go into wcm>General Options and click the Close Button binding to grab a key combination, and enter the key combo you use to close a window, what does it show up as?

**Comment by librewish** [comment]
<alt> KEY_F4

shows when i enter the 
alt + f4

also 
print key is not recognised when pressed by wcm

**Comment by soreau** [comment]
It seems you are suggesting a change of the default from KEY_FN_F4 to KEY_F4. You can open a new wayfire issue report about this. For the print button, please open a new wcm issue.
