### ISSUE TITLE
some keybinding are not detected 

### ISSUE THREAD

**Issue by librewish** [WayfireWM/wcm#14]
print key
media keys like play pause next prev
are not detected in wcm

**Comment by soreau** [comment]
I can not reproduce this. Print Screen/SYSRQ and media keys work with and without modifiers on the keyboard I tested here. Have you tried your device with `evtest` to make sure you're getting events from it as you expect?

**Comment by librewish** [comment]
those keys work 
when i manually set them in wcm.
but the key grabber doesnt detect them

**Comment by soreau** [comment]
I am specifically referring to the grabber. These keys grab fine here.

**Comment by soreau** [comment]
What are the key code names of the keys you're having trouble with?

**Comment by soreau** [comment]
because if a key doesn't start with `KEY_` or `BUTTON_`, there might be a problem.

**Comment by soreau** [comment]
Also make sure you have latest wayfire, since before, the grabber won't detect keys that are already bound to a binding.

**Comment by librewish** [comment]
i cant run latest wayfire
it wont compile with the wlroots in arch repo.
so i tried compiling with wlroots-git
but it doesn't start it crashes.
i have made an issue but no one replied to it.

**Comment by soreau** [comment]
You mean wayfire #327?

**Comment by librewish** [comment]
yes
from that time i cant start wayfire
i tried to compile it multiple times with wlroots-git
it wont start.
so some commit must have caused it.

**Comment by soreau** [comment]
Have you tried rebuilding latest wlroots-git and wayfire-git today? You would need to upgrade both for compatibility.

**Comment by librewish** [comment]
i have not tried today.
 i will try it again and see if wayfire works.
and report

**Comment by librewish** [comment]
okay tried today
and now wayfire works
and those keys also are detected.
so you can close the issue.
just one thing 
why does the wayfire-plugins-extra
need to be built against newer wayfire version everytime wayfire is updated

**Comment by ammen99** [comment]
@librewish When wayfire is updated, plugins need to be updated too. We can't avoid this (consider if some function in Wayfire changes, the plugin needs to be updated)
