### ISSUE TITLE
numlock / kb_capslock_default_state option in input

### ISSUE THREAD

**Issue by Arnaudv6** [WayfireWM/wcm#19]
Thanks for this awesome project!

**Comment by soreau** [comment]
[This](https://github.com/WayfireWM/wayfire/blob/master/metadata/input.xml#L24-L33) already exists. You need at least [this](https://github.com/WayfireWM/wayfire/commit/f670ee3e215fc7d425952a8b276e5d66213db8f5) wayfire commit.

**Comment by Arnaudv6** [comment]
ok, sorry... just compiled from git. should have done it beforehand
