### ISSUE TITLE
[switcher] Plugin always turned off in GUI

### ISSUE THREAD

**Issue by nwg-piotr** [WayfireWM/wcm#20]
Even if I check the Switcher check box (or "Use This Plugin" in plugin setting), it remains turned off, as if settings had not been saved. Adding `switcher` to `plugins =` in wayfire.ini works as expected.

**Comment by nwg-piotr** [comment]
It works, still the check box isn't being refreshed on startup.

![image](https://user-images.githubusercontent.com/20579136/96354017-f59f5000-10d1-11eb-9acd-b464b3de618f.png)

**Comment by soreau** [comment]
There are other commits that should fix it, just make sure you have latest git.

**Comment by nwg-piotr** [comment]
Confirmed.
