### ISSUE TITLE
Output configuration is missing in wcm

### ISSUE THREAD

**Issue by librewish** [WayfireWM/wcm#24]
# Output configuration ─────────────────────────────────────────────────────────

# Example configuration:
#
# [eDP-1]
# mode = 1920x1080@60.000000
# layout = 0,0
# transform = normal
# scale = 1.000000

This is in wayfire.ini

But why cant it be configured using wcm ?

Please add it in wcm

**Comment by jamdox** [comment]
+1 for this.  Maybe having wlr-randr as a dependency and using it to populate a dropdown?

**Comment by soreau** [comment]
As of https://github.com/WayfireWM/wcm/commit/cf45ff597791eede99a8f8ab818bca0938fc8f90, wcm now builds wdisplays as a subproject and installs a button to launch it if it's found in PATH.
