### ISSUE TITLE
Resetting some colors doesn't work

### ISSUE THREAD

**Issue by NamorNiradnug** [WayfireWM/wcm#33]
When resetting some colors to defaults in WCM, the options don't change. I noticed that resetting **works** if default color is represented as four numbers in metadata (like in [crosshair plugin](https://github.com/WayfireWM/wayfire-plugins-extra/tree/master/metadata/crosshair.xml#L16)) and doesn't work if it is represented as `#RRGGBBAA`.

**Comment by soreau** [comment]
Can you check if this patch fixes all the cases?

**Comment by NamorNiradnug** [comment]
Yes, seems like it does.
