### ISSUE TITLE
Using gtkmm instead of plain gtk?

### ISSUE THREAD

**Issue by NamorNiradnug** [WayfireWM/wcm#40]
Devs, would you accept a PR with rewriting of the project to gtkmm? Tbh, plain C-style GTK code is pretty hard to read and change.

**Comment by soreau** [comment]
I think this is a great idea, if it can be done without sacrificing functionality. It should make the code easier to organize and maintain. If you make a PR, I will review and test it. Thanks for all your work on wayfire!
