### ISSUE TITLE
Crash in input editor

### ISSUE THREAD

**Issue by UltraBlackLinux** [WayfireWM/wcm#42]
Hey there,
I just noticed that wcm is crashing on 0.7.0.r9.g2b139dc-2. Clicking on the tabs Mouse, Keyboard and Cursor each crash the tool with the following exception:

```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
zsh: IOT instruction (core dumped)  wcm
```
Please fix this!
Thanks!

**Comment by soreau** [comment]
Works fine here, are you sure you've rebuilt wayfire and wcm against latest wf-config?

**Comment by UltraBlackLinux** [comment]
Well, now I know, why I had wcm-git installed when I thought I didn't need it
