### ISSUE TITLE
Tile plugin outdated

### ISSUE THREAD

**Issue by ammen99** [WayfireWM/wcm#5]
The new tiling plugin and autorotate are missing. Would be nice to have them for the 0.3 release, even though the config system will be reworked for 0.4.

**Comment by ammen99** [comment]
Oh the vswipe plugin is missing too...

We do need to merge the XMLs, wf-config and the plugins.

**Comment by soreau** [comment]
Should be fixed with b491f09, a0d0b2a and fed750a.
