### ISSUE TITLE
Wdisplays is dead but is still a subproject

### ISSUE THREAD

**Issue by epsilon-0** [WayfireWM/wcm#62]
Seems like upstream has abandoned the project, so it should probably not be packaged here, unless wcm is using any specific parts of the project.

**Comment by NamorNiradnug** [comment]
Hi.
Well, Wdisplays works, so I don't think we should rewrite it or use something else.
Maybe we should fork it and maintain our own fork?

**Comment by marcusbritanicus** [comment]
Indeed it works, and works great. I guess new commits would make sense only if something was broken or improved. Also, what would we do by simply forking it?

However, I have a suggestion: if we do decide to fork, it would be much better if we could integrate it with the rest of wcm. What I mean is that, wdisplays currently directly applies the configuration and has no mechanism to save it. It would make much more sense to save the configuration to the Wayfire config file and let Wayfire to apply the configuration.

**Comment by hosiet** [comment]
I noticed that there is an active fork of wdisplay at https://github.com/artizirk/wdisplays . Should the subproject be modified to link there instead of the current (dead) github repo?

**Comment by soreau** [comment]
> I noticed that there is an active fork of wdisplay at https://github.com/artizirk/wdisplays . Should the subproject be modified to link there instead of the current (dead) github repo?

Yes, most definitely.
