### ISSUE TITLE
wcm crashes when loading autostart page if <type>...</type> tag is removed

### ISSUE THREAD

**Issue by marcusbritanicus** [WayfireWM/wcm#66]
The `autostart.xml` file shipped by wayfire has a few [badly formatted lines](https://github.com/WayfireWM/wayfire/blob/master/metadata/autostart.xml#L13-L15). Ideally, they should be:

```
<entry prefix="" type="string">
	<hint>file</hint>
</entry>
```

Note that the entry `type` is already defined in the `<entry ... >` tag as an attribute. When this correction is made, and we open the `autostart` plugin page, wcm crashes.

PS: this can also be a problem in wfconfig and wcm, but I am not sure.

**Comment by soreau** [comment]
As discussed on irc, removing [this conditional](https://github.com/WayfireWM/wcm/blob/master/src/wcm.cpp#L803-L806) solves it, possibly related to [this](https://github.com/WayfireWM/wcm/blob/master/src/metadata.cpp#L176).
