### ISSUE TITLE
Please avoid implicit dependency on which(1) command (use "command -v" if possible)

### ISSUE THREAD

**Issue by hosiet** [WayfireWM/wcm#72]
https://github.com/WayfireWM/wcm/blob/6b28ffc6e8948085eecf533514bedc7a467ff86d/src/wcm.cpp#L1437

The `which` command is not guaranteed to exist in a POSIX environment. For a portable way of detecting the existence of a command, consider using something else like `command -v`.

**Comment by soreau** [comment]
Fixed with https://github.com/WayfireWM/wcm/commit/fb9dd5746c077f60a34ff1f70d7ef3f70e5a59b5 which is also in 0.8.x branch for upcoming 0.8.1 release soonish.
