### ISSUE TITLE
CC-BY 2.0 licensed icons are not considered compatible with Debian

### ISSUE THREAD

**Issue by hosiet** [WayfireWM/wcm#74]
I submitted wcm for inclusion of Debian, and got the following rejection response:

>  as the CC 2.0 license is not compatible with DFSG, please remove all icons under this license from the source tarball.

According to https://wiki.debian.org/DFSGLicenses#Creative_Commons_Attribution_1.0_Generic_.28CC_BY_1.0.29 , Debian does not consider CC 1.0 and 2.0 licenses to be compatible with Debian DFSG guidelines. If possible, please replace them with icons of a compatible license as listed on https://wiki.debian.org/DFSGLicenses (such as CC-BY 3.0 or CC-BY 4.0 licenses).

The following search shows all incompatible icons:

* https://github.com/search?q=repo%3AWayfireWM%2Fwcm+by-sa&type=code

> [icons/plugins/plugin-blur.svg](https://github.com/WayfireWM/wcm/blob/fb9dd5746c077f60a34ff1f70d7ef3f70e5a59b5/icons/plugins/plugin-blur.svg?plain=1#L114)
> [icons/plugins/plugin-obs.svg](https://github.com/WayfireWM/wcm/blob/fb9dd5746c077f60a34ff1f70d7ef3f70e5a59b5/icons/plugins/plugin-obs.svg?plain=1#L184)

**Comment by hosiet** [comment]
@soreau  With some further review, I highly doubt whether #75 is legit. Obviously the Wayfire project is not the icon author; why could these icons be relicensed from CC-BY-2.0 to CC-BY-4.0 without explanation?

These icons appear to be the work of @jimmac , and I believe the changing of license should get a prior approval.

**Comment by jimmac** [comment]
I am not the author of either of those.

**Comment by soreau** [comment]
@jimmac Thank for for chiming in.

@hosiet The icons in question were from compiz. They reportedly were originals from coz_ who has made most of the other icons for WCM. I spoke with them on IRC and they said these icons were theirs, and authorized the license update. I could have probably put some form of explanation in the commit message, but I did not. I'm not sure how you would like to proceed, but I'm open to whatever needs to be done to get past this hurdle.

**Comment by hosiet** [comment]
@soreau  Thanks for the info, I think these are good enough. I will update the documentation on my side accordingly.
