### ISSUE TITLE
wcm can not change animation duration anymore. 

### ISSUE THREAD

**Issue by mark-herbert42** [WayfireWM/wcm#79]
Most likely it happened after teh commit changing the duration value from number to a string  
https://github.com/WayfireWM/wayfire/pull/2202

**Comment by soreau** [comment]
This is a known problem since durations now have optional easing types. Here is [a patch](https://termbin.com/kd1a) to fix it but it's not completed yet. Once it is, we can make a new release of wcm.

**Comment by marcusbritanicus** [comment]
Just ran into this issue... The patch does not seem to apply.

```
❯ curl https://termbin.com/kd1a | git apply
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7791  100  7791    0     0   3072      0  0:00:02  0:00:02 --:--:--  3073
error: patch failed: src/metadata.cpp:51
error: src/metadata.cpp: patch does not apply
```

Am I doing something wrong?

**Comment by mark-herbert42** [comment]
patch is not awailable anymore. I was thinking to rebase and  give it a try but file not found  anynore

**Comment by soreau** [comment]
Can anyone interested test [this patch](https://termbin.com/c112)? Looking for proper functionality for 1) Set duration 2) Set easing 3) Reset to Default (using the right button in the same row of buttons as the setting).
