### ISSUE TITLE
autorotate-iio.xml and vswitch.xml

### ISSUE THREAD

**Issue by librewish** [WayfireWM/wcm#8]

**Comment by ammen99** [comment]
Can you describe what is the issue?

**Comment by librewish** [comment]
super + up
super+ left
super + down
super + right.

are repeated.
same keycombo
for autorotate and vswitch

**Comment by ammen99** [comment]
This looks like a problem with the .xml file for autorotate-iio, the default keybindings should be `<ctrl><super>KEY_*` (but this is still a bug on our side)
