### ISSUE TITLE
wcm dosent save settings

### ISSUE THREAD

**Issue by snakee-arch** [WayfireWM/wcm#92]
the wcm app dosent save current setting (enabling a plugin) only changing a keybind works, so i need to change the config of my wayfire.ini and that defeats the purpose of wcm, is there any fix?

**Comment by NamorNiradnug** [comment]
Hi!
Could you please specify which versions of WCM and wayfire are you using?

**Comment by soreau** [comment]
Check the location and permissions of the config file.

**Comment by soreau** [comment]
Also, check the output of wcm (in a terminal) for any interesting related messages.

**Comment by snakee-arch** [comment]
i just chmoded my wayfire.ini file to make it from read to read write, and it worked thanks!

**Comment by snakee-arch** [comment]
i just chmoded my wayfire.ini file to make it from read to read write, and it worked thanks!
